### PR TITLE
Add GH Pages site

### PR DESCRIPTION
**Pull request by Medallyon**
Quickly whipped up this page to be hosted with GitHub Pages. To enable, merge this PR, go to settings, enable GitHub Pages for **Source**: `master branch`.

This page simply loads the `README.md` table and displays it on the page. Make any changes as you wish.

### CODE REVIEW

**Comment by Medallyon** [comment]
For a preview of what this would look like, go to https://medallyon.github.io/bandinchina

Once merged, this would become `caffeine-overload.github.io/bandinchina`.

**Comment by dmathisen** [comment]
This is awesome!
Suggestions...
1 - make the 'date' columns `white-space: nowrap;` for readability
2 - make the entire table (or at least the "why added" column) `text-align: left;` also for readability

**Comment by Medallyon** [comment]
Sure, thanks for the suggestions. Only thing I'm not sure about is that `:nth-child` is being used this much, but I can't think of another way to do this.

**Comment by caffeine-overload** [comment]
So merge now then?

**Comment by Medallyon** [comment]
If you think it's good, 👍. Can always make changes down the line.

**Comment by dmathisen** [comment]
Maybe add classes to the columns?
`<td class="no-wrap">...</td>` and `<td class="text-left">...</td>`?
But whatever. Looks good!

Also, ideally, a link should be added to the main readme.md page...

**Comment by Medallyon** [comment]
> Maybe add classes to the columns?
> `<td class="no-wrap">...</td>` and `<td class="text-left">...</td>`?

Totally forgot those classes exist. Doesn't make a difference, really.

I might revise it later to make sure only the table is being read and rendered, not the whole `.md` file.

**Comment by caffeine-overload** [comment]
Thanks so much for your contribution

**Comment by caffeine-overload** [comment]
I've just noticed an issue, the webpage is mashing the source urls together

**Comment by caffeine-overload** [comment]
The first link, for example, points to https://edition.cnn.com/2019/10/08/tech/hearthstone-hong-kong-intl-hnk-scli/%20https://kotaku.com/blizzard-suspends-hearthstone-player-for-hong-kong-supp-1838864961%20https://playhearthstone.com/en-us/blog/23179289

**Comment by Medallyon** [comment]
Ah I didn't realise there are multiple links in the sources tab. Should be an easy fix.

**Comment by caffeine-overload** [comment]
I'm clueless when it comes to web programming

**Pull request merged**
