### PR TITLE
Add Nike removing rockets from more stores

### PR DESCRIPTION
**Pull request by Valansch**
Updated the nike entry:
- Add archive link
- Add Date
- Add removal from physical stores

### CODE REVIEW

**Comment by caffeine-overload** [comment]
The code constructing the github page does not like the archive links, so maybe no archive links yet until that is figured out

**Comment by Valansch** [comment]
I'm not sure what you mean, they look fine for me:
image

If you can point me to the problem I can either try to get around that, or remove the links.

**Comment by caffeine-overload** [comment]
Its the algorithm @Medallyon wrote in the html page, I don't think it understands the markdown style text hyperlink

**Comment by Valansch** [comment]
Okay i removed the archive links.

**Pull request merged**
