### PR TITLE
added Google

### PR DESCRIPTION
**Pull request by strgalt-t**
added Google's censorship of an app about Hong Kong revolution

### CODE REVIEW

**Comment by caffeine-overload** [comment]
The explanation google gave was "Apps can't profit from current conflict", so I'm not sure if it counts. 

The litmus test of course would be to make a game about another current conflict and see if google ban it as well, if anyone is up for that

**Comment by riccalioliojr** [comment]
> The litmus test of course would be to make a game about another current conflict and see if google ban it as well, if anyone is up for that

There should already be some existing games that falls under this category. Just search for the word 'duterte'. Most of these games are about the current drug war conflict in the Philippines.

**Comment by strgalt-t** [comment]
If this doesn't count, Google showed with Project Dragonfly that they are willed to bound to censorship for financial gain, they should be on the list anyhow

**Comment by smiller171** [comment]
@strgalt-1 but employees were able to get that shut down, showing the anti-authoritarian faction within Google still has a bit more power.

**Comment by riccalioliojr** [comment]
> @strgalt-t but employees were able to get that shut down, showing the anti-authoritarian faction within Google still has a bit more power.

These are the last news I remember about the Dragonfly project:

https://www.theverge.com/2019/3/4/18250285/google-dragonfly-censored-search-engine-code-dead-employees-doubt

https://theintercept.com/2019/03/27/google-dragonfly-china-review/

So there is still uncertainty that they indeed shut it down...

**Comment by strgalt-t** [comment]
I mean it shows that the company itself is more than willed to work for the Chinese government and submit to censorship, that the employees could put it on a halt (probably) is great

**Comment by caffeine-overload** [comment]
Yeah, the scope of this repo is a bit vague but I think Google making a search engine in China that censors (as required by law) doesn't really hit the scope. Feel free to reopen if you disagree, but Google didn't censor or punish speech in the west, they didn't punish another western company and they didn't produce a political apology.

**Pull request closed without merging**
