### PR TITLE
Add GitHub itself to the list

### PR DESCRIPTION
**Pull request by cirosantilli**

### CODE REVIEW

**Comment by caffeine-overload** [comment]
They are still up as far as I can tell, unless I'm mistaken it looks like github published China's letter but didn't take action. I would be grateful if you could give information about if any repositories were taken down, or news media reports

**Comment by cirosantilli** [comment]
They are only blocked on the country that blocks them as mentioned on the README: https://github.com/github/gov-takedowns

This is an official GitHub controlled repo, https://github.com/github (verified), so I don't think there is need for third party verification.

**Comment by ronchaine** [comment]
I can access the repositories (except for one) in the takedown requests.

If they are blocked only in China, I see no problem with this.  Github (and/or any other company/organisation) are not (and should not) be exempt from breaking national laws when operating in the country in question.  If they took them down globally, I would agree with the PR.

**Comment by LenKagetsu** [comment]
The readme which you posted an excerpt from states that it will only be blocked in that region, which is perfectly reasonable. Complying with local laws when you serve an international community is hardly kowtowing, and is something GitHub must do to ensure the open source community retains as many users as it can. Region blocking content is a trivial matter, and this place has no shortage of programmers, and Microsoft has no shortage of money.

> > * limit the geographic scope of the takedown when possible and include that as part of the notification

**Comment by cirosantilli** [comment]
Yes, blocked in China only, if the policy here is "has to be visible outside of China", should not be merged.

**Comment by cirosantilli** [comment]
BTW, is the Apple entry any different? Blocks reported appear to be only in China, so only innocently complying with Chinese local law.

**Comment by cirosantilli** [comment]
Also Nike:

> Removed all Houston Rockets merch from their China stores (web and physical

**Pull request closed without merging**
