### PR TITLE
NBA did not apologize

### PR DESCRIPTION
**Pull request by vonmoltke**
The NBA did not issue China an apology, and Silver says they will not do so: https://chicago.suntimes.com/2019/10/8/20904593/nba-china-commissioner-adam-silver-no-apology

### CODE REVIEW

**Comment by caffeine-overload** [comment]
I based the entry on such news as https://www.independent.co.uk/news/world/asia/houston-rockets-hong-kong-protests-china-nba-tencent-apology-twitter-a9146211.html

This is quite confusing. Could it be Silver is trying to save face in the west? Or that some parts of the organisation panicked and issued apologies in haste?

**Comment by vonmoltke** [comment]
This is confusing.  The Independent article references the NBA's Chinese
language media, which the Sun Times doesn't talk about.  I don't see how
China will be happy or satisfied with Silver and the NBA saying different
things in different venues, particularly when they conflict.

**Comment by caffeine-overload** [comment]
I've added Silver's comments, I guess whether the NBA stays on the list or not depends on their long term stance and actions

**Comment by vonmoltke** [comment]
OK, I'll close this then.

**Pull request closed without merging**
