### PR TITLE
Remove Nike and Apple from the list because their ban was in China / HK only

### PR DESCRIPTION
**Pull request by cirosantilli**
At https://github.com/caffeine-overload/bandinchina/pull/56 I have been
informed that only bans that affect countries outside of China should be
added to this repository:

> But I'm closing this on the basis that github didn't censor the pages outside of China thus didn't export Chinese censorship, so it isn't a serious enough action to be added to the list.

The current Nike and Apple cases appear to be only effective in China or
HK, so for this reason I recommend removing them from the list to keep
things consistent.

Sorry, I couldn't resist the temptation to try and prove that I'm right. I gave in to weakness and broke one of my fundamental rules.

If the reason whey #56 was closed was because "blocking a few political websites in a given country only" is not serious enough though, do close this. But is it really less serious than the removal of the TW emoji or Houston Rockets merch? I would argue not.

:heart: :heart: :heart:

### CODE REVIEW

**Comment by caffeine-overload** [comment]
For the purposes of this, I'm counting HK and Macau as "not in China" because of the different legal system and no great firewall

The Nike one is a bit of a grey area, but from what I can see, even though it took place in China, they punished another western company, going above and beyond what was required of them by Chinese law in an apparent attempt to impress the Chinese. So it does break that one rule I put, but I felt like this deserved an exception. 

Github on the other hand, is not proactively banning repositories, only banning if the Chinese government send them a letter pointing out specific repositories, and they then publish the letter which I am sure the Chinese are not happy about. 

That is my line of reasoning at the moment. Obviously I will reconsider github if their bans extend to HK

**Comment by ronchaine** [comment]
I feel HK makes sense with "not in China" because of the reasons @caffeine-overload stated, I am not familiar with how Macau works so cannot comment on that.

The thing is, that line of inclusion has to be somewhere (and I think Chinese legal system is pretty good one), otherwise this would just become a list of every company operating in China, since every company operating in China needs to adhere to Chinese law.  And that is exactly how it should be, being an international company is no excuse to break local laws, even if you might disagree with those.

That is no different from breaking local laws in e.g. Germany.  Sites offering content there have to adhere to German laws, and for example take down / block sites for Germans about Holocaust denial, which is illegal there.

**Comment by cirosantilli** [comment]
Thanks for clarifying caffeine-overload and ronchaine.

HK / Macau / TW rule is clear for me.

One possible nobler alternative for companies would be "I don't comply with censorship", and get out of the country if it is required (the downside being that the West would lose a way to spy on China). But sure, no company ever does that since they just care about money, better leave that to a whitelist.

About Nike, I see the logic, but if the commies made a law saying that "you can't sell Houston shirts", would that make you remove it from the list?

Laws mean little in dictatorships, where "subverting state power" is illegal, and any reference to anything against state power such as Houston shirts could be considered illegal at any moment.

In any case, feel free to close this issue, you guys are :trophy: :trophy: :trophy:.

**Comment by caffeine-overload** [comment]
Thanks for your input

If China made a law now, Nike will stay on this list because they made the first move. 

If Nike instead protested such a law and left China, cutting off their access to all the money, they would be choosing principle over profit and they would go on the whitelist.

If I were to include all western companies that complied with Chinese law within mainland China, the list would be too long and lose its impact.

**Pull request closed without merging**
