### PR TITLE
[Feature] Make table sortable and initial sort by company name

### PR DESCRIPTION
**Pull request by MobiDotS**
Added sortable library to sort table.

### CODE REVIEW

**Comment by MobiDotS** [comment]
For some reason Github is adding extra spaces and whatnot to my PR. Feel free to push a commit that formats it properly.

**Comment by MoistCode** [comment]
Functionality looks good. One thing that you might want to add is to make it more prominent that users are able to click on the headers to sort.

Perhaps add an icon or something like this:

Screen Shot 2019-10-31 at 3 27 15 PM

**Comment by MobiDotS** [comment]
@MoistCode Good idea! Added FontAwesome for the icons.

image

**Comment by caffeine-overload** [comment]
Ready to merge?

**Comment by MobiDotS** [comment]
Let's do it.

**Pull request merged**
